-- AlterTable
ALTER TABLE "daily_revenues" 
ADD COLUMN "sitting_revenue" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "takeaway_revenue" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN "delivery_revenue" DOUBLE PRECISION NOT NULL DEFAULT 0;
